image:
  repository: awsmman/logrotate-operator
  tag: "1.0.0"
  pullPolicy: IfNotPresent

operator:
  namespace: logrotate-operator
  replicas: 1

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
