apiVersion: apps/v1
kind: Deployment
metadata:
  name: logrotate-operator
  namespace: {{ .Values.operator.namespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app: logrotate-operator
  template:
    metadata:
      labels:
        app: logrotate-operator
    spec:
      serviceAccountName: {{ include "logrotate-operator.serviceAccountName" . }}
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["kopf"]
        args: ["run", "--standalone", "/app/operator-logrotate.py"]
